# Generated by Django 5.2.3 on 2025-06-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_profile_delete_choosefeatures_delete_profilefeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, default='Write something that other people will see', max_length=500, null=True),
        ),
    ]
